# Generated by Django 4.2.10 on 2024-04-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.CharField(max_length=100)),
                ("step_count", models.IntegerField()),
                ("current_status", models.CharField(max_length=100)),
            ],
        ),
    ]
